<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7a6e7f45df45bff018bb83f2d1bee1af
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twbs\\Bootstrap\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twbs\\Bootstrap\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7a6e7f45df45bff018bb83f2d1bee1af::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7a6e7f45df45bff018bb83f2d1bee1af::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7a6e7f45df45bff018bb83f2d1bee1af::$classMap;

        }, null, ClassLoader::class);
    }
}
